version: "3.9"

services:
  db:
    image: postgres:16
    container_name: spydb
    environment:
      - POSTGRES_USER=spy
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=spy
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spy -d spy"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: spy-adminer
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    profiles: ["tools"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spy-tracker-app
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql+psycopg2://spy:pass@db:5432/spy
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    profiles: ["full"]

volumes:
  db_data:

