services:
  - type: web
    name: SPY-tracker
    env: docker
    plan: starter
    region: oregon
    autoDeploy: true
    healthCheckPath: /healthz
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      # Secrets set in dashboard will not be overwritten
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

