#!/bin/bash

# Development Startup Script for SPY TA Tracker
# This script starts both frontend and backend services
# Generated by Agent OS to prevent setup amnesia

set -e  # Exit on error

echo "🚀 Starting SPY TA Tracker Development Environment"
echo "================================================="

# Load environment variables
if [ -f .env ]; then
    echo "📋 Loading backend environment from .env"
    export $(grep -v '^#' .env | xargs)
fi

if [ -f .env.local ]; then
    echo "📋 Loading frontend environment from .env.local"
    export $(grep -v '^#' .env.local | xargs)
fi

# Get ports from environment or use defaults
BACKEND_PORT=${API_PORT:-8000}
FRONTEND_PORT=${PORT:-3000}

echo ""
echo "📡 Starting Backend Server on port $BACKEND_PORT..."

# Check if backend directory exists
if [ -d "backend" ]; then
    cd backend
    
    # Check if virtual environment exists
    if [ -d ".venv" ]; then
        echo "   Activating Python virtual environment..."
        source .venv/bin/activate
    else
        echo "⚠️  Virtual environment not found. Creating one..."
        uv venv
        source .venv/bin/activate
    fi
    
    # Install/update dependencies if requirements files exist
    if [ -f "requirements.txt" ]; then
        echo "   Installing/updating Python dependencies..."
        uv pip install -r requirements.txt
    elif [ -f "pyproject.toml" ]; then
        echo "   Installing/updating Python dependencies..."
        uv pip sync pyproject.toml
    fi
    
    # Start backend server in background
    echo "   Starting FastAPI server..."
    uvicorn app.main:app --reload --port $BACKEND_PORT &
    BACKEND_PID=$!
    
    cd ..
else
    echo "❌ Backend directory not found!"
    exit 1
fi

echo ""
echo "🎨 Starting Frontend Server on port $FRONTEND_PORT..."

# Check if package.json exists (frontend directory)
if [ -f "package.json" ]; then
    # Install/update dependencies
    echo "   Installing/updating Node.js dependencies..."
    yarn install
    
    # Start frontend server in background  
    echo "   Starting Vite development server..."
    yarn dev &
    FRONTEND_PID=$!
else
    echo "❌ Frontend package.json not found!"
    kill $BACKEND_PID 2>/dev/null || true
    exit 1
fi

echo ""
echo "✅ Development servers started!"
echo "   Frontend: http://localhost:$FRONTEND_PORT"
echo "   Backend:  http://localhost:$BACKEND_PORT"
echo "   API Docs: http://localhost:$BACKEND_PORT/docs"
echo ""
echo "📱 SPY TA Tracker Features:"
echo "   • Morning prediction form (sub-60s entry)"
echo "   • Manual price capture (tap-to-log tiles)" 
echo "   • Real-time chart visualization"
echo "   • Prediction vs actual price tracking"
echo ""
echo "Press Ctrl+C to stop all services"

# Function to cleanup background processes
cleanup() {
    echo ""
    echo "🛑 Shutting down development servers..."
    kill $BACKEND_PID 2>/dev/null || true
    kill $FRONTEND_PID 2>/dev/null || true
    echo "✅ All services stopped"
    exit 0
}

# Trap Ctrl+C and call cleanup
trap cleanup INT

# Wait for background processes
wait